
sudo: false
language: node_js

node_js:
- '5.5.0'

before_install: npm install -g grunt-cli
install: npm install
before_script: grunt concat

script:
- grunt test

branches:
    only:
        - master
